Algoritmo "numero"   //mostre o menor
//Disciplina:[Linguagem e Lógica de Programação]
//Professor: Edilene Aparecida Veneruchi de Campos
//Descrição:
//Autor: Cristiano Perira Alves de Morais
//Data:13/03/2022

Var
num1,num2,menor: real


Inicio

escreva("Qual o número 1? ")
leia (num1)
escreva ("Qual o número 2? ")
leia (num2)

se (num1<num2) entao
escreva ("O numero menor é,", num1)
senao
escreva ("O numero menor é, ", num2)
fimse


Fimalgoritmo